name: Update eMAG Feed

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Generate feed
        run: |
          python generate_feed.py

      - name: Commit updated feed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add feed.xml
          git commit -m "Auto update feed" || echo "No changes"

          git push
